default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

development:
  <<: *default
  database: omniauth_google_development

test:
  <<: *default
  database: omniauth_google_test

production:
  <<: *default
  database: omniauth_google_production
